### ISSUE TITLE
Checklist for Go/No-Go on integrating WebXR infrastructure in iOS Firefox 

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla-mobile/webxr-ios#172]
We need to have a clear idea of what needs to be done and working (and what that means) for us to decide we want to go ahead with getting WebXR into Firefox for iOS.  And what the timeline is.

**Comment by garvankeeley** [comment]
[ ] switch from Cocoapods to Carthage
[ ] remove any dependencies that aren't used by Firefox iOS

**Comment by robomex** [comment]
My latest commit to the 'develop' branch completes the switch from CocoaPods to Carthage and removes all dependencies that aren't used by Firefox for iOS.

**Comment by blairmacintyre** [comment]
- [ ] build minimal .js wrapper for injection, pull in rest of wrapper when xr used
- [ ] update immersive-web/webxr-polyfill to final version webxr
- [ ] update webxr-ios-js to final version of webxr
- [ ] decide which webxr AR non-standard features will be included (coordinate with Google?)
- [ ] finalize general permission flow (based on final webxr and iOS app design)
- [ ] add empty Metal canvas and a single JS api call to enable/disable "XR View" and specify configuration, so that UI can be tested on in FF iOS app with simple HTML page to enter XR (and XR UI bar to exit)
